### ISSUE TITLE
How to Run?

### ISSUE THREAD

**Issue by kuzeko** [BONSAMURAIS/arborist#9]
The README has a simple instruction to use the module in python code, but how to use it as a script. I can imagine something like "arborist -o time location" to have it output the ttl for time and locations.

**Comment by tngTUDOR** [comment]
Hi @kuzeko ,

There is indeed a main main script. You can figure this out by looking at the  `entrypoints` entry of the setup dictionnary in the `setup.py` script of the package. (https://github.com/BONSAMURAIS/arborist/blob/master/setup.py#L36 as of writing)

For arborist, this would be the `arborist-cli` (under arborist/bin/ ).
*However* I think the configuration is actually broken as of version `0.3.0` (from pypi).

**Comment by tngTUDOR** [comment]
If you git clone arborist and then run `python setup.py develop`, the `arborist-cli` is available and works fine (I am using  the following versions of packages)
```
# packages in environment at /home/tomas/miniconda3/envs/arborist-test:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
arborist                  0.3                       dev_0    <develop>
ca-certificates           2019.5.15                     0  
certifi                   2019.6.16                py37_0  
docopt                    0.6.2                    pypi_0    pypi
isodate                   0.6.0                    pypi_0    pypi
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
ncurses                   6.1                  he6710b0_1  
numpy                     1.16.4                   pypi_0    pypi
openssl                   1.1.1c               h7b6447c_1  
pandas                    0.24.2                   pypi_0    pypi
pip                       19.1.1                   py37_0  
pyparsing                 2.4.0                    pypi_0    pypi
python                    3.7.3                h0371630_0  
python-dateutil           2.8.0                    pypi_0    pypi
pytz                      2019.1                   pypi_0    pypi
rdflib                    4.2.2                    pypi_0    pypi
readline                  7.0                  h7b6447c_5  
setuptools                41.0.1                   py37_0  
six                       1.12.0                   pypi_0    pypi
sqlite                    3.28.0               h7b6447c_0  
tk                        8.6.8                hbc83047_0  
wheel                     0.33.4                   py37_0  
xlrd                      1.2.0                    pypi_0    pypi
xz                        5.2.4                h14c3975_4  
zlib                      1.2.11               h7b6447c_3  
```

but, if you do a `python setup.py install` you end up with a missing package:

 ```
Using /home/tomas/miniconda3/envs/arborist-test/lib/python3.7/site-packages
Finished processing dependencies for arborist==0.3
$ arborist-cli 
Traceback (most recent call last):
  File "/home/tomas/miniconda3/envs/arborist-test/bin/arborist-cli", line 11, in <module>
    load_entry_point('arborist==0.3', 'console_scripts', 'arborist-cli')()
  File "/home/tomas/miniconda3/envs/arborist-test/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/tomas/miniconda3/envs/arborist-test/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/home/tomas/miniconda3/envs/arborist-test/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/home/tomas/miniconda3/envs/arborist-test/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'arborist.bin'
```

**Comment by tngTUDOR** [comment]
It seems that the `__init__.py` file is missing from the `bin` directory.
I'll take a look later on how to upgrade using setuptools for the package.

**Comment by tngTUDOR** [comment]
I think this has been solved: the cli script is available when you follow the "install" instructions evoked in the README.
(Better packaging and publishing of this core tool of the BONSAI chain would require another issue to track and decide on the registries to use [conda-forge, bonsai, cmutel, pypi])
